### ISSUE TITLE
Sending multiple SMS at once

### ISSUE THREAD

**Issue by ghimes** [web2sms/composer#2]
From the documentation i can understand that it can send multiple SMS at once:

`$sendSMS->messages[]  =....` . 
but looking at src/SendSMS.php:13 I can see this:
`public function sendSMS(){
        foreach($this->validMessageList as $smsItem) {
            $response = $this->sendRequest($smsItem);
            return $response;
        }
    }`

Which means it will send only the first sms from the validMessageList. 

That means messages being an array of sms items make no sense.

**Comment by navid59** [comment]
Thanks for raising this issue
It has now been fixed
