### ISSUE TITLE
Message sending fails because of OpenSSL error

### ISSUE THREAD

**Issue by dandarie** [web2sms/composer#3]
Sending a message on a Ubuntu 20.04 LTS server with PHP 8.1.3 and curl 7.68.0  fails with output:

```
<warning>PHP Warning:  Undefined variable $http_code in /application/vendor/web2sms/sms/src/Web2sms.php on line 179</warning>
{"status":0,"code":null,"msg":null,"data":false}
```

Upon further investigation, the curl_exec call at src/Web2sms.php#L82 fails with: `error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`.

This can be fixed with: `curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'DEFAULT@SECLEVEL=1');` in src/Web2sms.php#L77

**Comment by navid59** [comment]
Is fixed now.
Thank you.
